using System;

namespace SharedKernel.Entities.Base;

/// <summary>
/// Resolves the domain type of an entity instance, looking through ORM-generated proxies.
/// </summary>
/// <remarks>
/// EF Core lazy-loading and change-tracking proxies are runtime subclasses of the entity type
/// (generated by Castle DynamicProxy under the <c>Castle.Proxies</c> namespace). Comparing
/// <c>GetType()</c> directly would make a proxied entity unequal to a plain instance with the same Id.
/// </remarks>
internal static class EntityTypeResolver
{
    private const string ProxyNamespace = "Castle.Proxies";

    internal static Type GetEntityType(object entity)
    {
        var type = entity.GetType();

        return type.Namespace == ProxyNamespace && type.BaseType is { } baseType
            ? baseType
            : type;
    }
}
